#!/usr/bin/env python3
"""Embed the canonical prompt text into webapp/provenance.html.

The app ships the real prompt text so that copy/paste works from the page
alone, with no repo checkout. That means the page carries a SECOND COPY of
files whose canonical home is prompts/. This repo already has one stale
duplicate of a live prompt (reference/shared-primitives.txt), so the copy here
is handled deliberately rather than casually:

  - every embedded prompt carries its canonical path, byte count and a
    sha256 prefix, all displayed in the UI;
  - the page states a snapshot date and says plainly which copy wins;
  - re-running this script re-syncs the page from disk, so the copy is
    regenerable rather than hand-maintained.

The generated HTML stays committed and hand-editable. This script is a
convenience for re-syncing after a prompt edit, NOT a required build step:
nothing downstream consumes its output except the page itself.

Usage:
    python3 tools/embed_prompts.py            # rewrite the payload in place
    python3 tools/embed_prompts.py --check    # exit 1 if the page is stale
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "webapp" / "provenance.html"

BEGIN = "/* PROMPT-PAYLOAD:BEGIN - generated by tools/embed_prompts.py */"
END = "/* PROMPT-PAYLOAD:END */"

# id -> canonical repo path. The ids are what the app's stage graph refers to.
SOURCES = {
    "0-field-diagnostic":    "prompts/0-field-diagnostic.txt",
    "1-claim-extraction":    "prompts/1-claim-extraction.txt",
    "2-construct-validity":  "prompts/research-analysis/2-construct-validity.txt",
    "2-internal-validity":   "prompts/research-analysis/2-internal-validity.txt",
    "2-citation-network":    "prompts/research-analysis/2-citation-network.txt",
    "3-counter-audit":       "prompts/research-analysis/3-counter-audit.txt",
    "2-framing-construction": "prompts/media-analysis/2-framing-construction.txt",
    "2-coverage-network":    "prompts/media-analysis/2-coverage-network.txt",
    "5-voice-restoration":   "prompts/5-voice-restoration.txt",
    "tool2-field-context":   "deferred/1-field-context-generator.txt",
    "retrieval-module":      "tools/citation_reception_module.py",
}


def build_payload() -> dict:
    prompts = {}
    for pid, rel in SOURCES.items():
        path = ROOT / rel
        if not path.exists():
            raise SystemExit(f"ERROR: missing source file: {rel}")
        raw = path.read_bytes()
        text = raw.decode("utf-8").replace("\r\n", "\n")
        prompts[pid] = {
            "path": rel,
            "text": text,
            "bytes": len(raw),
            "lines": text.count("\n") + 1,
            "sha256": hashlib.sha256(raw).hexdigest()[:12],
        }
    return {
        "snapshot": date.today().isoformat(),
        "note": (
            "Embedded copies. The files under prompts/ are canonical; if this "
            "page and the repo disagree, the repo wins."
        ),
        "prompts": prompts,
    }


def serialize(payload: dict) -> str:
    # ensure_ascii covers U+2028/U+2029 and every other non-ASCII permanently.
    # Escaping "<" makes "</script" unrepresentable while staying valid JSON --
    # "<" only ever occurs inside string values, so the replace is lossless.
    blob = json.dumps(payload, ensure_ascii=True, sort_keys=True, separators=(",", ":"))
    return blob.replace("<", "\\u003c")


def render_block(payload: dict) -> str:
    return (
        f"{BEGIN}\n"
        f"  var PROMPTS = JSON.parse({json.dumps(serialize(payload))});\n"
        f"  {END}"
    )


def main() -> int:
    check = "--check" in sys.argv[1:]

    page = PAGE.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END), re.S
    )
    if not pattern.search(page):
        raise SystemExit(
            "ERROR: payload markers not found in webapp/provenance.html.\n"
            f"Expected a block delimited by:\n  {BEGIN}\n  {END}"
        )

    payload = build_payload()
    # Preserve the existing snapshot date when nothing else changed, so a
    # no-op re-run does not produce a diff.
    existing = pattern.search(page).group(0)
    new_block = render_block(payload)
    if check:
        stale = _strip_snapshot(existing) != _strip_snapshot(new_block)
        print("STALE - re-run tools/embed_prompts.py" if stale else "up to date")
        return 1 if stale else 0

    m = re.search(r'\\"snapshot\\":\\"(\d{4}-\d{2}-\d{2})\\"', existing)
    if m and _strip_snapshot(existing) == _strip_snapshot(new_block):
        print("up to date - nothing written")
        return 0

    PAGE.write_text(pattern.sub(lambda _: new_block, page, count=1), encoding="utf-8")

    total = sum(p["bytes"] for p in payload["prompts"].values())
    print(f"embedded {len(payload['prompts'])} files, {total:,} bytes")
    for pid, p in sorted(payload["prompts"].items()):
        print(f"  {p['sha256']}  {p['bytes']:>7,}  {pid:<22} {p['path']}")
    print(f"page is now {PAGE.stat().st_size:,} bytes")
    return 0


def _strip_snapshot(block: str) -> str:
    return re.sub(r'\\"snapshot\\":\\"\d{4}-\d{2}-\d{2}\\"', "", block)


if __name__ == "__main__":
    raise SystemExit(main())
